### ISSUE TITLE
Trishula,  the Ice Prison Dragon [ Bug? ]

### ISSUE THREAD

**Issue by XiaErr** [Fluorohydride/ygopro-scripts#1090]
Hello.

I noticed something about the card " Trishula, the Ice Prison Dragon "

I think that according to the text it should be possible to revive that card with monster reborn for example, after that card is fusion summoned first then destroyed afterwards.

But for some reason the game doesn't give the chance to do that.

So, my question is,  if this is a bug? Or a ruling thing?  

Thanks.

**Comment by DailyShana** [comment]
fixed in https://github.com/Fluorohydride/ygopro-scripts/commit/e2506c91995b6541ee645c9f58b64be5749ef5e9#diff-628491288b90114bae4543a70b561077
