### ISSUE TITLE
DNA Transplant [ Bug? ]

### ISSUE THREAD

**Issue by XiaErr** [Fluorohydride/ygopro-scripts#1091]
Hello.

I think there's something wrong with the card 
" DNA Transplant " [56769674] 

After activating that card, for some reason it doesn't let you declare the "Wind" attribute, it's possible to declare all other attributes but not "Wind".

The same thing happens with the card
 " Elementsaber Nalu " [46425662]  when that card is in the graveyard.

It doesn't let you declare the "Wind" attribute either.

By the way, thanks for the attention and the hard work that all of you are doing to provide an amazing duel simulator for the benefit of the community.

**Comment by DailyShana** [comment]
Can't reproduce
