### ISSUE TITLE
Great General Of The Six Samurai

### ISSUE THREAD

**Issue by KieranJack** [Fluorohydride/ygopro-scripts#1120]
Great General's effect to add a bushido adding card currently is not activating. I have tested with united, gateway, dojo and daredevil in deck. My first guess would be that it is to do with requiring to be link summoned and it is perhaps only registering as a special summon but I haven't looked at the lua code

**Comment by DailyShana** [comment]
The scripts of LVP2 have not been added here, and it is probably you didn't update the old cards, see https://github.com/Fluorohydride/ygopro-pre-script/tree/master/scripts/LVP2-JP/update_old_cards/046
