### ISSUE TITLE
Doomking Balerdroch's interaction with Zombie World

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-scripts#1143]
The following ruling:

> Ｑ：《アンデットワールド》の適用中、《オルフェゴール・ディヴェル》を墓地から除外してその効果を発動しました。
> 　　この時、《オルフェゴール・ディヴェル》は墓地ではアンデット族、除外ゾーンでは機械族になりますが、《死霊王 ドーハスーラ》の(1)の効果は適用できますか？
> Ａ：ご質問の場合、墓地ではアンデット族でしたので、《死霊王 ドーハスーラ》の(1)の効果を発動することは可能です。(18/11/04)

[that can be found here](http://yugioh-wiki.net/?%A1%D4%BB%E0%CE%EE%B2%A6%20%A5%C9%A1%BC%A5%CF%A5%B9%A1%BC%A5%E9%A1%D5), roughly translated as:

> Q: During the application of "Zombie World", i banished "Orcust Harp Horror" from the graveyard and activated the effect.
> At this time, "Orcust Harp Horror" is an Zombie type in the graveyard, while it becomes a Machine type while banished, can the effect of (1) of the "Doomking Balerdroch" be applied?
> A: In the case of a question, since it was an Zombie type in the graveyard, it is possible to activate the effect of (1) of "Doomking Balerdroch". (18/11/4)
> 

currently does not work and you are unable to use Balerdroch's effect, [as can be seen in this puzzle](https://cdn.discordapp.com/attachments/291708361752313866/535852396866306057/baledroch_grave.lua). While one could think of an workaround for Doomking Balerdroch, only, it would be better if all the functions similar to **GetRace** had something like **GetPreviousRace** that takes the location as paremeter, instead of something as limited as **GetPreviousRaceOnField**.

**Comment by salix5** [comment]
fixed in f891606e923b0f26fbbd7353119c9fa6b47f9975
Thank you very much!

**Comment by NaimSantos** [comment]
While I do appreciate the fact that the issue has been acknowledged, the fact that only an workaround was implemented bothers me, as it looks like the real problem was ignored.

**Comment by salix5** [comment]
Old version: 
The activated monster's type is checked **after** paying the cost of Orcust Harp Horror, so its effect will be treated as "when a Machine type monster activates effect".

New version:
The operation of EFFECT_ACTIVATE_COST runs **before** paying the cost of Orcust Harp Horror.
Now the activated monster's type is checked **before** paying the cost of Orcust Harp Horror, so its effect will be treated as "when a Zombie type monster activates effect".

I believe that it will work in most situations. If you still find some bugs, please upload the replay files.

About utility function:
I am not sure how to do that, so I commit it in this way for now.

**Comment by AlphaKretin** [comment]
Naim is not saying that you didn't fix the issue, or that your change has bugs, but that the solution is short-term, and not ideal. We shouldn't need to use massive workarounds with global effects, the same way we don't need to if the race on the field matters. There should be a simple core function to check the previous race regardless of location, which would make dealing with these cards and any future similar ones much simpler.

**Comment by AndreOliveiraMendes** [comment]
for example, why does **GetPreciousRaceOnField**, more specific, why **OnField**? why start with something as limited as that? that shouln't be limited and should work the same way as GetPreviousLocation/Controler, there no reason to lock it to field, so these function either need to start maping previous race/atribute regard of location or have a param to specify the location.
