### ISSUE TITLE
"Arcana Force XXI - The World" interaction with "The Deep Grave"

### ISSUE THREAD

**Issue by AndreOliveiraMendes** [Fluorohydride/ygopro-scripts#1144]
We asked the OCG office a question regarding the turn skip effect of "Arcana Force XXI - The World" (アルカナフォースⅩⅩⅠ－ＴＨＥ ＷＯＲＬＤ) and how it interacts with "The Deep Grave" (深すぎた墓穴) and got this answer.

>Q.
相手メーンフェーズ時に、自分の「深すぎた墓穴」を発動します。
その後、同じターンでも、相手の「アルカナフォースⅩⅩⅠ－ＴＨＥ ＷＯＲＬＤ」の効果によって、次のターンをスキップします。
この状況で、「深すぎた墓穴」の『次の自分スタンバイフェイズにそのモンスターを墓地から自分フィールドに特殊召喚する。』の処理はどのように適用されますか？
A.
その場合も、次の自分のスタンバイフェイズにモンスターを特殊召喚できます。

Approximate translation:

>Q.
I activate "The Deep Grave" in my opponent's turn, then later in that same turn, my opponent uses the effect of "Arcana Force XXI - The World" to skip my next turn. In this case, how is the process of "The Deep Grave" Special Summoning applied?
A.
In that case you can Special Summon the monster during your next Standby Phase.

So the way I see it, "The World" skips your turn, then on your next turn (after the skipped turn) you still summon the monster targeted by "The Deep Grave".
I tested it, and it wasn't summoned, so it seems like the effect was reset during the skipped turn. There should be some kind of effect flag or other way to tell the core if an effect should be reset on a skipped turn or not.

**Comment by DailyShana** [comment]
no such problem after https://github.com/Fluorohydride/ygopro-core/commit/f87e6689cc5ec6e43fb44311a12c4abb110b12d3
