### ISSUE TITLE
2 "Sagitta, Maverick Fur Hire"[93738004] does not lock targeted effects.

### ISSUE THREAD

**Issue by Houssem-Guemer** [Fluorohydride/ygopro-scripts#1215]
i had 2 "Sagitta, Maverick Fur Hire"[93738004] face up on the field , wich should lock all targeted effect but "doomking balerdroch"[39185163] targeted "Beat, bladesman fur hire"[93850652] and banished it.

**Comment by nekrozar** [comment]
_Doomking Balerdroch_'s effect isn't target effect.

> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=14056
> ■『以下の効果から１つを選んで適用する』モンスター効果は**対象を取る効果ではありません**。
