### ISSUE TITLE
Bug:If the Equip Spell's effect is negated when it's activating,it will be send to the graveyard.

### ISSUE THREAD

**Issue by mallu11** [Fluorohydride/ygopro-scripts#1234]
Maybe can add "EFFECT_FLAG_CANNOT_DISABLE" into the <i>Property</i>.

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-core/blob/master/field.cpp#L3178
If effect has `EFFECT_FLAG_CANNOT_DISABLE`, `is_chain_disablable` return false.
So, it is better to use `EFFECT_FLAG_CONTINUOUS_TARGET`.

**Comment by DailyShana** [comment]
it's wrong, equip spell of cause can be disabled. It is just the taking equip target still applies even the activation is disabled.

**Comment by nekrozar** [comment]
> http://yugioh-wiki.net/?%C1%F5%C8%F7%CB%E2%CB%A1
> Ｑ：《ＴＧ ブレード・ガンナー》を対象として相手が装備魔法カードを発動し、それに対して《ＴＧ ブレード・ガンナー》の「効果を無効にする」効果を発動しました。
> 　　発動は無効にされず、効果のみ無効にされたその装備魔法カードは、通常通り装備される・効果を無効にして装備される・墓地へ送られる、のどれになりますか？
> 　　（またはそれ以外の別の処理になりますか？）
> Ａ：《ＴＧ ブレード・ガンナー》の効果を、装備魔法カードのカードの発動にチェーンして発動した場合、装備魔法カードは対象のモンスターに装備されます。
> 　　装備魔法カード自身が破壊される、装備モンスターがフィールドで表側表示で存在しなくなる、等にならない限り、効果が無効化された状況のまま**フィールドに存在し続けます**。(15/09/30)

**Comment by DailyShana** [comment]
I say the ideal of using EFFECT_FLAG_CONTINUOUS_TARGET is wrong.
When disable the effect of an equip spell, only the part of taking equip target applies, other operation should still be disabled.

**Comment by nekrozar** [comment]
> other operation

I didn't find similar that effect.

And, konami's answered these
![faq](https://user-images.githubusercontent.com/10573786/67729092-1d198a80-fa33-11e9-8773-9a60a518ef2a.png)
![faq](https://user-images.githubusercontent.com/10573786/67729117-2e629700-fa33-11e9-9994-4ddb74d9710c.png)
