### ISSUE TITLE
BUG: Red-Eyes Fusion after PR #1244

### ISSUE THREAD

**Issue by szefo09** [Fluorohydride/ygopro-scripts#1247]
### After PR #1244 Red-Eyes Fusion (6172122) can no longer fuse Dragun of Red-Eyes (100259001) using Dark Magician and any 1 Dragon Effect Monster from the deck. 

Current behavior: Red-Eyes Fusion activates only when you have "Red-Eyes" monster in your deck.

Screenshot shows the issue. 
In the deck there's a valid Effect Dragon Monster Fantastical Dragon Phantazmay (78661338).
![image](https://user-images.githubusercontent.com/37833135/68997682-68dc8880-08a9-11ea-80d6-0aa41796143f.png)

**Comment by edo9300** [comment]
Because that's the point of the ruling, you must use a red-eyes monster to fuse with red-eyes fusion

**Comment by Zey344** [comment]
Red-eyes fusion does fusion summon any Monster that has Red-eyes in his name but not material... So it can fusion summon using non- red-eyes monsters

**Comment by mallu11** [comment]
> Red-eyes fusion does fusion summon any Monster that has Red-eyes in his name but not material... So it can fusion summon using non- red-eyes monsters

According to the latest official faq,red-eyes fusion must use red-eyes monsters as material.

**Comment by Zey344** [comment]
Replied*

في السبت، ١٦ نوفمبر، ٢٠١٩ ١٠:٥٦ م mallu11 <notifications@github.com> كتب:
