### ISSUE TITLE
Absolute King Back Jack and similar cards vs Set Rotation

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-scripts#1254]
You cannot activate the first effect of **Absolute King Back Jack** if the player is affected by the "cannot Set" effect of **Set Rotation**, even though that only prevents you from setting Field Spells, not Trap Cards.

**Comment by nekrozar** [comment]
even though you cannot update core, maybe _Absolute King Back Jack_ can fix these code.
```lua
function c60990740.target(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then
		local ce={Duel.IsPlayerAffectedByEffect(tp,EFFECT_CANNOT_SSET)}
		for _,te in ipairs(ce) do
			local tg=te:GetTarget()
			if not tg then return false end
		end
		return Duel.IsPlayerCanDiscardDeck(tp,1) and Duel.GetLocationCount(tp,LOCATION_SZONE)>0
	end
end
```
