### ISSUE TITLE
Droll & Lock Bird can be activated during incorrect timings

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-scripts#1321]
For this, I am providing the lines for a puzzle so you can test and see it more easily.
In the puzzle, do the following:

# Scenario 1:

> 1-Pass the turn
> 2-Activate Reinforcement of the Army [this is the timing to activate Droll Lock Birb, but Mystic Mine is preventing that]
> 3 - Normal Summon Raye
> 4 - Replace Mystic Mine for Sky Striker Airspace - Area Zero
> Droll & Lock Bird can now be activated, which is incorrect. If Mystic Mine is not involved in this, the interaction works properly.

# Scenario 2: 

> 1-Pass the turn
> 2-Activate Reinforcement of the Army 
> 3-Replace Mystic Mine for Sky Striker Airspace - Area Zero
> 4-Chain Mystical Space Typhoon and destroy  Sky Striker Airspace - Area Zero
> Droll & Lock Bird can now be activated, which is incorrect. If Mystic Mine is not involved in this, the interaction works properly.

# Scenario 3:

> 1-Pass the turn
> 2-Activate Reinforcement of the Army
> 3-Replace Mystic Mine for Sky Striker Airspace - Area Zero
> Droll & Lock Bird can now be activated, which is incorrect. If Mystic Mine is not there, the interaction works properly.

Here is the puzzle's code
```
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

Debug.AddCard(94145021,0,0,LOCATION_HAND,0,POS_FACEDOWN)

Debug.AddCard(14536035,0,0,LOCATION_MZONE,1,1,true)
Debug.AddCard(19230407,0,0,LOCATION_SZONE,2,10)
Debug.AddCard(5318639,0,0,LOCATION_SZONE,4,10)
Debug.AddCard(26077387,1,1,LOCATION_DECK,0,POS_FACEDOWN)
Debug.AddCard(50005218,1,1,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(32807846,1,1,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(76375976,1,1,LOCATION_SZONE,5,5)

Debug.ReloadFieldEnd()
```

**Comment by DailyShana** [comment]
fixed in Fluorohydride/ygopro-core@4cc1b18511cd1ad81486a29a51780187c8d82ce9
