### ISSUE TITLE
Millennium-Eyes Restrict and name-changing effects

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-scripts#1322]
>Q: 
>A Millennium-Eyes Restrict equipped with SPYRAL Double Helix is face-up in my opponent's Monster Zone. In this situation, if I Link Summon a second SPYRAL Double Helix, are its effects negated?
>A:
>A face-up SPYRAL Double Helix is treated as SPYRAL Super Agent by its own effect. In this scenario, since Millennium-Eyes Restrict is equipped with a SPYRAL Double Helix, the effect of the SPYRAL Double Helix treated as SPYRAL Super Agent will not be negated.

From: www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=21564&keyword=&tag=-1)

> Q:
> A Millennium-Eyes Restrict equipped with SPYRAL Super Agent is face-up in my opponent’s Monster Zone. In this situation, if I Link Summon a SPYRAL Double Helix, are its effects negated?
> A:
> A face-up SPYRAL Double Helix is treated as SPYRAL Super Agent by its own effect. In this scenario, since Millennium-Eyes Restrict is equipped with SPYRAL Super Agent, the effect of SPYRAL Double Helix that reveals the top card of your opponent’s Deck will be negated. (Even so, its name will continue to be treated as SPYRAL Super Agent.)

From: www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=21563&keyword=&tag=-1

In the sample puzzle below, do the following:

1- Activate SPYRAL -Super Agent in the Hand
2- Millennium-Eyes Restrict equips a copy of SPYRAL-  Super Agent
3- Link Summon SPYRAL- Double Agent
4- Try to equip it with SPYRAL Gear - Fully Armed

You will notice that you cannot equip because the name changing effect was negated, which is wrong.

```
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

Debug.AddCard(30979619,0,0,LOCATION_DECK,0,POS_FACEDOWN)
Debug.AddCard(20584712,0,0,LOCATION_DECK,0,POS_FACEDOWN)
Debug.AddCard(1322368,0,0,LOCATION_EXTRA,0,8)
Debug.AddCard(41091257,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(73828446,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(83764718,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(41091257,0,0,LOCATION_GRAVE,0,POS_FACEUP)
Debug.AddCard(41091257,0,0,LOCATION_MZONE,0,1,true)
Debug.AddCard(41091257,0,0,LOCATION_MZONE,1,1,true)
Debug.AddCard(41091257,0,0,LOCATION_MZONE,3,1,true)
Debug.AddCard(35699,1,1,LOCATION_DECK,0,POS_FACEDOWN)
Debug.AddCard(41578483,1,1,LOCATION_MZONE,2,1,true)
Debug.ReloadFieldEnd()


```

**Comment by salix5** [comment]
[disable_name.zip](https://github.com/Fluorohydride/ygopro-scripts/files/4840680/disable_name.zip)
Turn 3
Known issue
Not fixed yet.
