### ISSUE TITLE
Megamorph vs Solitary Sword of Poison

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-scripts#1323]
A monster equipped with `Solitary Sword of Poison` and`Megamorph` should have its ATK becoming **4x** its original attack during damage calculation, according to rulings. Currently, it is only doubled. 
[Source for the ruling](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=13060&keyword=&tag=-1&request_locale=ja)
Below I provide the setup for a puzzle to test it:

```
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)


Debug.AddCard(93377803,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(22046459,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(75878039,0,0,LOCATION_REMOVED,0,5)
Debug.AddCard(27174286,0,0,LOCATION_SZONE,1,10)
Debug.AddCard(13959634,1,1,LOCATION_MZONE,3,1,true)
Debug.ReloadFieldEnd()
aux.BeginPuzzle()
```

**Comment by DailyShana** [comment]
fixed in https://github.com/Fluorohydride/ygopro-core/commit/01ad314e045db4a274df8c0e35a2d2a5f553b706
