### ISSUE TITLE
Knightmare Unicorn vs Guarded Treasure

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-scripts#1412]
If `Guarded Treasure`  and `Knighmare Unicorn` are face-up in your field:

-if there any co-linked "Knightmare" monsters on the field, you will draw that ammount.
-in the opposite scenario, you will draw 1, but you should draw 2, due to `Guarded Treasure`.

This happens because of the  value used by Unicorn sets the draw ammount to 1 in case it does not find "Knightmare" monsters co-linked

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/a0b3cab227764d0990f8beb65fd030c69eb7a332
I guess this will fix it

**Comment by mercury233** [comment]
But according to the ruling, if both cards are in effect, the player should draw the max count among the effects.
