### ISSUE TITLE
Are there ways to confirm rules using in duel?

### ISSUE THREAD

**Issue by Wind2009-Louse** [Fluorohydride/ygopro-scripts#1424]
> Q.
自分の魔法＆罠ゾーンに「メタモル・クレイ・フォートレス」を含む5枚の魔法・罠カードがセットされています。
自分のモンスターゾーンに「幻創龍ファンタズメイ」が表側表示で存在しています。
この状況で、「幻創龍ファンタズメイ」を対象として、セットされている「メタモル・クレイ・フォートレス」を発動できますか？
A.
ご質問の状況の場合、「メタモル・クレイ・フォートレス」を発動でき、「幻創龍ファンタズメイ」は装備カード扱いとなります。

According to the newest Q&A, you can activate [Metamorphortress](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=12510&request_locale=ja) even if you have no empty place in Spell&Trap Zone. But in ygopro-core, only Master Rule 2020 make Trap Monster not occupying Spell&Trap Zone. So, [Metamorphortress](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=12510&request_locale=ja) should be able to activate even if not enough Spell&Trap Zone in Master Rule 2020, but unable in other rules.
Therefore, how to confirm current rule using in duel?

**Comment by DailyShana** [comment]
write the scripts in current ruling
for old rule, waiting for https://github.com/Fluorohydride/ygopro-core/pull/257 or https://github.com/Fluorohydride/ygopro-core/issues/271
