### ISSUE TITLE
Dragon Knight Draco-Equiste vs Raidraptor - Readiness (REFLECT_DAMAGE vs NO_DAMAGE)

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-scripts#1434]
The opponent controls `Dragon Knight Draco-Equiste`. I activate the graveyard effect of  `Raidraptor - Readiness`, so I do not take damage for the rest of the turn. If I then activate `Hinotama` Equiste will still make me receive that damage, which is incorrect.

**Comment by salix5** [comment]
Do you have the replay file?
Thank you.

**Comment by NaimSantos** [comment]
Setup: ```
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

--Hand
Debug.AddCard(6552938,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(46130346,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(5318639,0,0,LOCATION_HAND,0,POS_FACEDOWN)
--GY
Debug.AddCard(21648584,0,0,LOCATION_GRAVE,0,POS_FACEUP)
Debug.AddCard(73887236,0,0,LOCATION_GRAVE,0,POS_FACEUP)

Debug.AddCard(21844576,1,1,LOCATION_GRAVE,0,POS_FACEUP)
Debug.AddCard(44508094,1,1,LOCATION_GRAVE,0,POS_FACEUP)
--Monster Zones
Debug.AddCard(14017402,1,1,LOCATION_EXTRA,3,10,true)
Debug.AddCard(81223446,1,1,LOCATION_SZONE,3,10,true)

Debug.AddCard(52503575,1,1,LOCATION_SZONE,4,1,true)
Debug.ReloadFieldEnd()
```

**Comment by salix5** [comment]
fixed
Thank you.
