### ISSUE TITLE
Confusion regarding strings on cards

### ISSUE THREAD

**Issue by Lyris12** [Fluorohydride/ygopro-scripts#1460]
There's a string missing at `aux.Stringid(93717133,1)`, aka `Galaxy-Eyes Photon Dragon`. `Cyber Tutubon` is similar: it has no strings in the database, yet it uses `aux.Stringid(42600274,0)`. Here are some other cards with similar issues to the 2 mentioned above:
- [ ] `Hieratic Dragon of Su`: `aux.Stringid(3300267,2)`
- [ ] `Hieratic Dragon of Nebthet`: `aux.Stringid(31516413,2)`

What are these strings supposed to say?

**Comment by mercury233** [comment]
mark it was special summoned, due to the special summon will release monster too

**Comment by Lyris12** [comment]
So, just say it `was Special Summoned`? Is there a reason that is so?

**Comment by mercury233** [comment]
The opponent may can't know it was special or normal summoned

**Comment by Lyris12** [comment]
Ohhh, I see, now! After all, not all YGOPRO clients support playing sounds!

**Comment by Lyris12** [comment]
Thanks, @mercury233!
