### ISSUE TITLE
[Bug] Duck Dummy - 43803845

### ISSUE THREAD

**Issue by SoaringSky** [Fluorohydride/ygopro-scripts#1466]
**Duck Dummy (43803845)**
> This card is treated as a Normal Monster while face-up on the field or in the GY. While this card is a Normal Monster on the field, you can Normal Summon it to have it become an Effect Monster with these effects.
> ● Cannot be destroyed by card effects. Neither player can target this card with card effects.
> ● The attacks from your opponent's monsters become direct attacks.

**Current behavior:** This card affects opponent's monsters who are unaffected by monster effects which causes those monsters to attack directly.

**Expected behavior:** The opponent's monsters that are unaffected should be able to attack monsters normally.

**Ruling:** https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=12823&request_locale=ja

> Question:
> A Master Peace, the True Dracoslaying King that is unaffected by Spell and monster effects is face-up on my field. In this situation, if Duck Dropper is face-up on my opponent's field and its effects are applying, how can Master Peace, the True Dracoslaying King attack?

> Answer:
> In this scenario, Master Peace, the True Dracoslaying King is unaffected by monster effects, so its attacks do not become direct attacks by the effect of Duck Dropper, and it can attack monsters normally.

**Example:**
![f9c912f5631b91af3fbb8fb157dff5c7](https://user-images.githubusercontent.com/49380069/89949631-36707980-dbf6-11ea-9f1b-8aea4399aaeb.gif)

**Comment by purerosefallen** [comment]
What is the above client?

**Comment by SoaringSky** [comment]
The gif above was recorded using Dueling Nexus. The issue was replicated on Koishipro before I submitted this Issue though.

**Comment by mercury233** [comment]
sorry for the la~~zy~~te response, now `EFFECT_IGNORE_BATTLE_TARGET` should check the attack monster too.

**Comment by SoaringSky** [comment]
Thank you Mercury. I know @Lyris12 was looking into fixing it, but this solution works too.
