### ISSUE TITLE
[Bug] 13629812 - Select Token as Target Will Crash

### ISSUE THREAD

**Issue by wyykak** [Fluorohydride/ygopro-scripts#1468]
To be more exact, calling Card.SetCardTarget() with an non-existing card(e.g. destroyed token) as parameter will crash the game.

**Comment by mallu11** [comment]
i think should use `tc:IsLocation(LOCATION_REMOVED)`.

**Comment by mallu11** [comment]
https://github.com/Fluorohydride/ygopro-scripts/pull/1469
