### ISSUE TITLE
Script bug Maharaghi id 40695128

### ISSUE THREAD

**Issue by sleeser** [Fluorohydride/ygopro-scripts#1471]
the card's effect in question: 

> This card cannot be Special Summoned. This card returns to the owner's hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. If this card is Normal Summoned or flipped face-up, **look at 1 card on the top of your Deck** during your next Draw Phase (before you draw), and return the card to the top or the bottom of your Deck.

With the current script, the top card is not being revealed, and during the next turn just the option to put in top or bottom deck is given which is not the desired behavior.

**Comment by mercury233** [comment]
![GIF](https://user-images.githubusercontent.com/13391795/90299406-8a19e600-dec8-11ea-9ec2-3d32031a00fb.gif)
no such problem here

**Comment by sleeser** [comment]
interesting, we tried it on both nexus and omega. maybe both sims are not parsing something then.

**Comment by sleeser** [comment]
Yea seems that it was just an issue on both sims rather then a script bug.
Sorry for any confusion this may have caused.
