### ISSUE TITLE
Amorphactor Pain non-chaining error.

### ISSUE THREAD

**Issue by kiwilover8** [Fluorohydride/ygopro-scripts#1516]
In the TCG, the card text for Amorphactor Pain, The Imagination Dracoverlord includes a : after the condition of "If this card is Ritual Summoned", the card text and associated script follow it as if it were a comma in the entry here, which means it does not start a chain and is instead automatic upon his summon.

**Comment by edo9300** [comment]
`"(1): If this card is successfully ritual summoned, skip Main Phase 1 of the next opponent's turn." Monster effects are not classified as activation effects, trigger effects, trigger immediate effects, or permanent effects`

**Comment by kiwilover8** [comment]
The issue is that the real life version of amorphactor pain is a triggered effect which occurs when the monster is summoned. The wording on the card in real life is "If this card is Ritual Summoned: Your opponent skips their next Main Phase 1." which is a trigger effect that starts a chain. The current version is incorrect
![Amorphactor](https://user-images.githubusercontent.com/4906091/103060277-7fe5b380-455c-11eb-9909-58aa5a370791.jpg)

**Comment by edo9300** [comment]
Ygopro uses ocg rulings, in ocg the effect is ruled ad unclassified, thus  the effect is implemented as such.
