### ISSUE TITLE
Issues with some destruction replacement effects

### ISSUE THREAD

**Issue by Lyris12** [Fluorohydride/ygopro-scripts#1787]
The following cards have `EFFECT_DESTROY_REPLACE` and can ignore destruction by rule or by another replacement effect:
```
Defender, the Magical Knight
Inzektor Ant
Koa'ki Meiru Prototype
Mermaid Archer
Vylon Tetra
Wind-Up Zenmaines
```
If someone can please look into this, that will be greatly appreciated.

**Comment by salix5** [comment]
Can you upload a replay file?
Thank you in advance.

**Comment by Lyris12** [comment]
Before I do so, am I allowed to use a Duel Replay of, say, a puzzle?

**Comment by salix5** [comment]
It's OK.
I just want to see an example.

**Comment by Lyris12** [comment]
Here you go: [test.zip](https://github.com/Fluorohydride/ygopro-scripts/files/7906039/test.zip) Extract this to your YGOPRO root folder. Let me know if something is not working, and I apologize in advance if so.
