### ISSUE TITLE
BUG: Thunder Dragon Fusion/Ultimate Fusion and other effects can’t use the cards affected by EFFECT_EXTRA_FUSION_MATERIAL as material.

### ISSUE THREAD

**Issue by mallu11** [Fluorohydride/ygopro-scripts#1861]
If a fusion effect can use cards in hand or on field as material, it should use _Duel.GetFusionMaterial(tp)_ otherwise it can’t use the cards affected by **EFFECT_EXTRA_FUSION_MATERIAL** as material.

**Comment by chronogenexx** [comment]
see https://github.com/Fluorohydride/ygopro-scripts/pull/1635.
