### ISSUE TITLE
BUG: Wrong argument passed in Utility.lua

### ISSUE THREAD

**Issue by Moterius** [Fluorohydride/ygopro-scripts#1933]
The Auxiliary.AddXyzProcedure scripts all pass the integer 1165 as the description to the created effect while the correct argument to pass would be 1165 IF AND ONLY IF the passed desc would be nil or negative. This causes the description to always be "XYZ Summon" instead of the correct one, if a description is given.
The issue shows up in the following two instances:
 - 689 (AddXyzProcedure)
 - 871 (AddXyzProcedureLevelFree)

**Comment by mercury233** [comment]
The `desc` here is the description for the alternative procecure such as Zoodiac Xyz monsters. Maybe them should be renamed.
