### ISSUE TITLE
Machina Fortress: bug?

### ISSUE THREAD

**Issue by Lyris12** [Fluorohydride/ygopro-scripts#1948]
Can `Machina Fortress` discard `Machina Cannon` and, say, `Machina Peacekeeper` for Fortress' procedure to Special Summon itself from the GY? If so, then why?

**Comment by mercury233** [comment]
Now in YGOPro it can only discard _Machina Cannon_ whose level is already 8, can't discard _Machina Peacekeeper_ if no other level 7 or lower Machina monster is in hand.

**Comment by Lyris12** [comment]
But is that correct in Konami's eyes?

**Comment by mercury233** [comment]
yes, you can't use 8+2 if the required is 8

**Comment by Lyris12** [comment]
I am hearing that the Pebble Rule only applies to Ritual Summoning effects...

**Comment by mercury233** [comment]
Them should be same as them are using same text.
