### ISSUE TITLE
BUG: `Extra Pendulum`

### ISSUE THREAD

**Issue by Lyris12** [Fluorohydride/ygopro-scripts#2082]
Is allowed to be activated more than once per turn, despite its lingering Pendulum Summon-granting effect being hard-once-per-turn

Source: https://forum.duelistsunite.org/t/extra-pendulum-is-completely-broken/16484

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/692c2e0f26278342a37bbf2d12bed36e7848a46a fixed
