### ISSUE TITLE
BUG: `Madolche Puddingcess Chocolat-a-la-Mode`

### ISSUE THREAD

**Issue by Lyris12** [Fluorohydride/ygopro-scripts#2084]
Last effect should not be once-per-Chain.

Source: https://forum.duelistsunite.org/t/error-with-the-resolution-of-madolche-chateau/16307

**Comment by mercury233** [comment]
■『②：このカードが「[マドルチェ・プディンセス](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=10156)」をX素材としている場合に自分の墓地の「マドルチェ」カードがデッキに戻った時、このカードのX素材を１つ取り除いて発動できる。デッキから「マドルチェ」モンスター１体を表側攻撃表示または裏側守備表示で特殊召喚する』モンスター効果は、誘発効果です。（対象を取る効果ではありません。この効果を発動する際に、コストとして、このカードのエクシーズ素材を１つ取り除きます。この効果は１ターンに複数回発動する事ができますが、**同一チェーン上にて複数回発動する事はできません**。また、ダメージステップでは発動する事ができません。）
