### ISSUE TITLE
Ties of the Berthren

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro-scripts#268]
when I activate Ties of the Berthren, in next turn after I activate it I still can't Special summon and Declare Attack. I hope it can be fixed

PS : I use Percy's YGOPRO
![untitled](https://cloud.githubusercontent.com/assets/11270664/13032129/0b6c776a-d29c-11e5-931a-c0f2d44eb174.JPG)

**Comment by marikisthar** [comment]
another (clear) image shown there's no pendulum summon activation and no BP icon
![ties](https://cloud.githubusercontent.com/assets/11270664/13032191/fd354576-d29d-11e5-9c9a-245916397037.JPG)

**Comment by mercury233** [comment]
It seems that only you encounter this problem. Please reinstall latest **full** version. If the problem still exists, ask on [YGOPRO Percy forum](http://www.ygopro.co/).
