### ISSUE TITLE
SpeedRoid Ohajikid

### ISSUE THREAD

**Issue by Kynalfa** [Fluorohydride/ygopro-scripts#48]
You can't use this card for summoning Red-Eyed Dice then use the effect of red eyed dice to put SpeedRoid Ohajikid to lvl 5 to summon HighSpeedRoid dahma for exemple.

Normaly you should be able to do it because when you use the Ohajikid effect that allows you to summon a tuner from either graveyard, at the end of that effect, you have to summon a wind synchro monster but when you summon Red-Eyed Dice, his effect normally apply before the end of the Ohajikid effect as a chain.

**Comment by destdev** [comment]
No, that effect works just like every single other "after this effect resolves, synchro/xyz/etc summon" effect, there is no chance to activate anything bevore the actual summon of the monster type. If you summon dice with the effect the resulting monster must be level 4, you can't change the level.
Also note, you can never "chain" anything while another effect is resolving, until the chain link of an effect of any card, including ohajikid is completely resolved you can't activate anything else inbetween.
The only thing that the term "immediatly after this effect resolves, summon [..]" allows is the usage of cards like solemn warning, black horn of heaven, etc on the summon of the xyz/synchro (and only if the effect in question is chain link 1) which wouldn't be possible without that.
