### ISSUE TITLE
Toon Kingdom is buggy?

### ISSUE THREAD

**Issue by fervi** [Fluorohydride/ygopro-scripts#486]
Some things described here may be against the rules.

1) If your opponent uses Toon Kingdom, you can not use your cards with Toon effects. I'm not an advanced player YGO, but most (or all) field spells used by all.

2) The situation of work when you and your opponent have Toon Kingdom, and you have a monster. If you use the spell you want to destroy your opponent Toon Kingdom that you can also lose monsters.

**Comment by mercury233** [comment]
Yes, most of the Toon monsters are silly. Them require Toon World on the player own field, but will be destroyed when Toon World is destroyed from any field.
