### ISSUE TITLE
Super Charge

### ISSUE THREAD

**Issue by Kynalfa** [Fluorohydride/ygopro-scripts#49]
You can't use this trap card with any of the new speed roid i think.

Normally if your opponent attacks you when you have only machine type monster whose name have "Roid" inside it. You can draw 2 cards.

But when i tried using it when i had High speed roid dahma, it doesn't trigger and i can't use it after as well.

**Comment by destdev** [comment]
That's a database issue and has nothing to do with the scripts.
Contact the one who is in charge of the database in the Ygopro version you are using for that one.
