### ISSUE TITLE
The supposed change of ruling by lullaby of obedience:

### ISSUE THREAD

**Issue by Mr-Andy-ygo** [Fluorohydride/ygopro-scripts#538]
from this update:

https://github.com/Fluorohydride/ygopro-scripts/commit/32cd639fa7115e14c0c2142f92a1ea272272ab97

That is completely wrong! totally! it's the biggest mess that could happen!

Lullaby of obedience is a card that forces the opponent to resolve it's effect. The card specifically states that he searches for the card and chooses what to do with it if he finds it. That is what makes it COMPLETELY DIFFERENT from the 32 cards changed in that update. The reason for that difference is that yugioh is played by a code of honor and such if the Turn Player is resolving a legal activation, he's not supposed to give proof that he's able to resolve it the way he does (in this case, proof that he does not have the card). Lullaby is a card that's comparable to setting a monster in your spell/trap zone when you play infernities or demonstrating that you have a psychic in your hand when you banish tincan for a Kozmo machine monster while Rivalry of Warlords is on the field: a judge can only be called if there are reasons to suspect the opponent is cheating.

That is completely, utterly, totally different to these 32 cases, and it should never be extrapolated. Also, because the card verification is explicitly stated in both the OCG and TCG tournament policies, that update must be reverted as soon as possible, because right now the game is being played in a wrong manner in Devpro.

Thanks for your time developing the system, and by the way, there seems to be no way to get the forum's verification email through so I couldn't register in the devpro forum to report the bug there.

**Comment by mercury233** [comment]
Please say those to KONAMI, because them say those **and this** card don't contain "confirm opponent's deck" effect, so it should be left over to judge.

> Question
自分が「天声の服従」を発動し、『相手は自身のデッキを確認し、宣言されたモンスターがあった場合、その内の１体をお互いに確認し以下の効果から１つを選択して適用する』処理が行われた場合、自分は相手のデッキの内容を確認する事はできますか？
Answer
「天声の服従」の効果処理によって、デッキの内容を確認するのは、
「天声の服従」を発動したプレイヤーから見て相手となるプレイヤーのみです。（相手プレイヤーが自身のデッキを確認します。）
「天声の服従」の効果処理によって、「天声の服従」を発動したプレイヤーは相手のデッキの内容を確認する事はできません。
相手プレイヤーが自身のデッキを確認した結果、宣言されたモンスターがあった場合、『宣言されたモンスターがあった場合、その内の１体をお互いに確認し以下の効果から１つを選択して適用する』処理を行う際に、その相手プレイヤーが選んだ1体を「天声の服従」を発動したプレイヤーも確認する事になります。
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=19408&keyword=&tag=-1

**Comment by Mr-Andy-ygo** [comment]
Lullaby of obedience is an unique case as already explained, because the own card text states that the opponent resolves it.

**Comment by mercury233** [comment]
So you should talk to KONAMI instead. The ruling in their database **explicitly** say only the opponent of Lullaby of obedience can confirm his deck.

**Comment by Mr-Andy-ygo** [comment]
Because the opponent of lullaby can. That is right... for lullaby. The problem is that this update changes that for other cards when konami has NEVER changed these cards.

Seriously... I wonder why I even wrote in my 1st post why Lullaby is totally different to all the other cards changed if it seems you're not even going to read it -.-

**Comment by mercury233** [comment]
Actually I didn't found the difference. And the ruling of cards like Chain Disappearance and Mind Crush had changed too.
https://github.com/Fluorohydride/ygopro/issues/1758
