### ISSUE TITLE
Search for : !counter 0xb

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro-scripts#552]
hi ,
in the strings.conf , i can find the script for all counters , except this one : 
`!counter 0xb 指示物（古代的机械城）`

in ygopro (english) , its "Counter(Ancient City)" , but google-translated its "(mechanical ancient city)"
i cant find a script that uses that counter
i looked for a card in ygopro , and the crystal beast ancient city is the only one with the name but it doesnt use counters

any help to find a script that uses that counter , please ?

thank u

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c92001300.lua#L45

**Comment by DailyShana** [comment]
It is [Ancient Gear Castle](http://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=6578&request_locale=en)

if you encounter problems in ygopro (english), you should contact the author of ygopro (english) first

**Comment by Hello23-Ygopro** [comment]
thank you for being helpfull @mercury233 , your very helpfull and contribute alot to ygopro always

im gonna give you +1 : )
