### ISSUE TITLE
Magical Something[43930492] , missing count ?

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro-scripts#595]
hi ,
just looked at magical something's script
since it sets a card in your spell/trap zone , what happens when your zones are all occupied?

Shudn't there also be this code :
`and Duel.GetLocationCount(tp,LOCATION_SZONE)>0`

in the target function ?
```
function c43930492.settg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
if chk==0 then return Duel.IsExistingTarget(c43930492.setfilter,tp,LOCATION_GRAVE,0,1,nil) end
```

unless the source code says its not needed , same reason why `Card.IsDestructable` was removed i think ..

**Comment by mercury233** [comment]
unlike `IsCanBeSpecialSummoned`, `IsSSetable` check zone available at default. 
`bool Card.IsSSetable(Card c[, bool ignore_field=false])`

**Comment by Hello23-Ygopro** [comment]
@mercury233 ah thanks, i didnt know that

ill look for some more like that in data-editorx's functions list
