### ISSUE TITLE
Incomplete procedure for "Crystron Glyongandr"

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-scripts#639]
The Synchro Procedure for "[Crystron Glyongandr](http://yugioh.wikia.com/wiki/Crystron_Gliongandr)" doesn't seem to fully work. I can Synchro Summon it without problems using monsters on the field, but if I try doing it with cards that use Materials from the hand, it simply doesn't work. 
Here's an example: I have "[Mara of the Nordic Alfar](http://yugioh.wikia.com/wiki/Mara_of_the_Nordic_Alfar)" on the field (Tuner, LV2) and "[Vanadis of the Nordic Ascendant](http://yugioh.wikia.com/wiki/Vanadis_of_the_Nordic_Ascendant)" (Tuner, LV4) and "[Tanngnjostr of the Nordic Beasts](http://yugioh.wikia.com/wiki/Tanngnjostr_of_the_Nordic_Beasts)" (non-Tuner, LV3) in the hand. With 2 Tuners and 1 non-Tuner I should be able to summon Glyongandr, but it doesn't work. I don't know if the error is with Glyongandr or in Mara (something similar happens with "[Tyrant Red Dragon Archfiend](http://yugioh.wikia.com/wiki/Tyrant_Red_Dragon_Archfiend)" too, so it might be an issue with Mara), but in either case I think it needs to be addressed.

**Comment by destdev** [comment]
related: https://github.com/Fluorohydride/ygopro/issues/1810

**Comment by mercury233** [comment]
please reopen this if any issue of this card still exists
