### ISSUE TITLE
Destruction Swordsman Fusion: Spell Speed 2

### ISSUE THREAD

**Issue by YGO5upp0r73r** [Fluorohydride/ygopro-scripts#652]
I was playing a Buster Blader deck today, and thought I could add [Destruction Swordsman Fusion](http://yugioh.wikia.com/wiki/Destruction_Swordsman_Fusion) to my hand during my opponent's turn, since it's a [Quick-Play Spell Card](http://yugioh.wikia.com/wiki/Quick-Play_Spell_Card) (Spell Speed 2).

Quick-Play Spell Cards are like Trap Cards - both have Spell Speed 2, so all their effects can be activated and applied, during either player's turn. They can even banish themselves from the Graveyard during either player's turn (unless their own effect is limited to a particular Phase).
They don't have to state, "_**During either player's turn: You can banish this card from your Graveyard...**_", but if they do state "_**During either player's turn**_", they also tend to include, "_**except the turn this card was sent to the Graveyard**_".

Shouldn't Destruction Swordsman Fusion's second effect that adds itself to your hand be a Quick Effect?
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c41940225.lua#L17

> If this card is in your Graveyard: You can send 1 card from your hand to the Graveyard; add this card to your hand.

The effect is not limited to a particular Phase, and doesn't have any other restrictions. Since it's a Quick-Play Spell Card, it should be a Quick Effect, unless I'm mistaken...

Edited: The other Quick-Play "Destruction Swords" are also Ignition Effects.

**Comment by mercury233** [comment]
> ■『②：このカードが墓地に存在する場合、手札を１枚墓地へ送って発動できる。墓地のこのカードを手札に加える』効果は墓地にて発動し、チェーンブロックの作られる効果です。（対象を取る効果ではありません。**自分のメインフェイズにのみ発動する事ができます**。また、この効果を発動する際に、コストとして、手札を1枚墓地に送ります。）
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=12167

Spell cards are different from trap cards, even though it is Quick-Play.

**Comment by YGO5upp0r73r** [comment]
It's incredible, I've played the game for so long, and I knew that. You learn something new every day!

Arigatou.
