### ISSUE TITLE
[Percy] Gandora the Dragon of Destruction card bug

### ISSUE THREAD

**Issue by fervi** [Fluorohydride/ygopro-scripts#759]
https://youtu.be/-4i9qKBXMGo

**Comment by salix5** [comment]
http://yugioh-wiki.net/index.php?%A1%D4%BF%C0%A4%CE%C0%EB%B9%F0%A1%D5
Ｑ：ライフポイントが１の状態でこのカードを発動できますか？
Ａ：できます。ライフを計算する場合、小数点以下は四捨五入します。
　　よって１÷２＝0.5となり四捨五入でライフポイントは１、つまり実質ノーコストで発動できます。

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=9994&keyword=&tag=-1
Question
フィールド上に存在する「破壊竜ガンドラ」以外のフィールド上に存在するカードを全て破壊しゲームから除外する効果を、同一ターン中に複数回発動する事はできますか？
Answer
「破壊竜ガンドラ」の効果によって、破壊して除外する事のできるカードがフィールド上で存在するのであれば、同一ターン中に「破壊竜ガンドラ」の効果を複数回発動する事ができます。

In OCG ruling,  "pay half your LP" means that your LP is halved, and Yugioh uses "Round half up" while rounding,
If your LP is 1, you can activate  "pay half your LP" effects infinitely many times.

In real world, the judge can stop a player from doing meaningless action and delaying the game deliberately, and how to stop AI from doing this is the problem of AI scripts.
