### ISSUE TITLE
There's a problem when I try to mix Greydle with Kaiju monsters

### ISSUE THREAD

**Issue by sybridge** [Fluorohydride/ygopro-scripts#820]
I've attached the replay file of the issue I'm frustrated about. They say that github doesn't accept yrp file, so I changed the file name. You can just fix it into .yrp again and see what's the problem. The part I want you to see is at the end of the replay.
![gameciel](https://cloud.githubusercontent.com/assets/26239478/23640384/9376cf46-0330-11e7-9967-63d541ff76ac.jpg)

When I try to control 2 Kaiju monsters at the same moment, thus intending to drop off the one which was placed on the opponent's field, sometimes the both Kaiju monsters are dumped into the graveyard. (Sometimes they do, sometimes not.)
I would be really grateful if you fix this problem on the next version of the app. Thanks for reading me!

**Comment by mercury233** [comment]
Sorry but I wonder if this issue still exist in latest version. Can you produce a new replay?
