### ISSUE TITLE
utility.lua error after update

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro-scripts#828]
With the new link procedure included we got a lot of errors from utility.lua. After asking around I've been told that it might be due to exceeding the max file size limit. (64 kb)
The updated file has 66 kb. I have no idea if you are aware of that issue or if you updated that limit in recent client/core changes, we haven't updated that yet.
I hope you can resolve this issue, or if it already is resolved please state what we need to update.

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@bd1b039
Fluorohydride/ygopro@eaf2e72
