### ISSUE TITLE
Clashing Souls (57496978) stops working after a certain amount of loops

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro-scripts#849]
For some reason the loop for applying ATK suddenly stops after both players paid 4000 LP total, (assuming both battling monsters have <500 ATK difference, tested with 8000 starting LP for both players). There is no error message or any visable reason why this happens, chk seems to become false even if there is enough of everything in order to be able to return true.

**Comment by destdev** [comment]
I've found the error, it seems something is wrong with Duel.CheckLPCost in this situation.
It returns false once halfe of any players lp is paid, I don't know why. Once that point is reached that player can't continue to pay LP.
I've created a workaround for this now, just use
local lp=Duel.GetLP(tc:GetControler())-500
and in the if check
lp>=0
it works with that and you can pay LP until you have no LP left to pay
however I think it should be better if you search for the error in the Duel.CheckLPCost function
unfortunately I don't have any experience here and can't help you with that one :/

**Comment by mercury233** [comment]
fixed
