### ISSUE TITLE
Magical Arm Shield -  	96008713

### ISSUE THREAD

**Issue by Oz-Projects** [Fluorohydride/ygopro-scripts#85]
Hi,
In a duel my opponent had two monsters (Red Eyes Zombie Dragon and a set down) and me one (Zombie Master), when he attacks me, game does not ask if i want activate Magical Arm Shield or not. 

Can it be fixed, please ?

**Comment by destdev** [comment]
there is no bug in your situation, read the card properly please:
Target 1 **face-up** monster your opponent controls, **except the attacking monster**;

there wasn't another face up monster on the opponents field, thus you didn't have a target

**Comment by Oz-Projects** [comment]
Ok thanks it's a translaction error then.
