### ISSUE TITLE
OpenYGO: Man-Eater Bug like card

### ISSUE THREAD

**Issue by fervi** [Fluorohydride/ygopro-scripts#863]
Hello.

I am developer of OpenYGO
We created the equivalent of the Man-Eater Bug, we took the script from this repository and replaced the ID number with the corresponding one in the project (2). But unfortunately it does not work.

I thought maybe someone from here would know what the problem was

[Script Error]: [string: "./script/c2.lua"]:5: attempt to index global 'aux' (a nil value)
YGOPro number: 54652250

I understand the error message (say), but I do not know what is causing it

INSERT INTO "datas" VALUES(2,3,0,0,2097185,500,700,3,8,32,0);
INSERT INTO 'texts' VALUES(2,'Shadow Grabbler','FLIP: Target 1 monster on the field, destroy it.','','','','','','','','','','','','','','','','');

**Comment by fervi** [comment]
http://meshnet-users.tk/paste/p/ajxy/q.txt
Card script

**Comment by mercury233** [comment]
did you add `utility.lua` to the script folder of your project?

btw, the id of card should be between 1000 and 268435455 if you didn't change the ygopro core.

**Comment by fervi** [comment]
Ok, it fix this problem
I also change id card numeration from 1000
