### ISSUE TITLE
List of cards that may need to be updated to use GetLocationCountFromEx etc.

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-scripts#882]
Those cards contain effect that summoning themselves from extra deck. Some of them weren't updated to the new rule.

SUMMON_TYPE_SYNCHRO:
- [x] 13455674
- [x] 16172067
- [x] 33541430
- [x] 3966653
- [x] 42291297
- [x] 62242678
- [x] 67030233
- [x] 7841112
- [x] 80896940
- [x] 87460579
- [x] 93157004
- [x] 97489701

EFFECT_SYNCHRO_MATERIAL_CUSTOM:
- [x] 33541430
- [x] 55863245
- [x] 57261568
- [x] 64910482
- [x] 89818984

SUMMON_TYPE_FUSION:
- [x] 2129638
- [x] 43387895
- [x] 72378329

EFFECT_FUSION_MATERIAL：
- [x] 19261966
- [x] 20366274
- [x] 31111109
- [x] 48424886
- [x] 74009824
- [x] 74822425
- [x] 94977269

SUMMON_TYPE_XYZ:
- [x] 23187256
- [x] 43490025
- [x] 52653092
- [x] 57314798
- [x] 57707471
- [x] 58600555
- [x] 65305468
- [x] 85004150

Misc(Contact Fusion etc.):
- [x] 11502550
- [x] 12678870
- [x] 1561110
- [x] 1686814
- [x] 17032740
- [x] 2111707
- [x] 22638495
- [x] 25119460
- [x] 27346636
- [x] 28677304
- [x] 29357956
- [x] 29432356
- [x] 30864377
- [x] 3779662
- [x] 43378048
- [x] 48063985
- [x] 48156348
- [x] 48996569
- [x] 49352945
- [x] 5128859
- [x] 53315891
- [x] 55171412
- [x] 56655675
- [x] 58859575
- [x] 65172015
- [x] 73285669
- [x] 78512663
- [x] 79229522
- [x] 80532587
- [x] 81566151
- [x] 84243274
- [x] 85507811
- [x] 86274272
- [x] 90884403
- [x] 90957527
- [x] 91998119
- [x] 99724761

**Comment by Hello23-Ygopro** [comment]
Thank you !! 👍👍
