### ISSUE TITLE
Unable to activate The Light - Hex-Sealed Fusion

### ISSUE THREAD

**Issue by tspivey** [Fluorohydride/ygopro-scripts#903]
With the latest ygopro-core (commit 2835740b) and ygopro-scripts (commit 17eb4eb4), The Light - Hex-Sealed Fusion can no longer be activated.

Using Master Rule 3, put the following cards in a deck:
* Cyber Dragon (70095154)
* The Light - Hex-Sealed Fusion (15717011)
* Cyber Twin Dragon (74157028)
* Giant Flea (41762634) -- put in enough of these to pad the deck.

1. Player 0 summons Giant Flea, and ends the turn.
2. Player 1 special summons Cyber Dragon.
3. Player 1 summons The Light - Hex-Sealed Fusion.
4. At this point, player 1 should be able to activate The Light - Hex-Sealed Fusion to special summon Cyber Twin Dragon from the extra deck.

Testing with git bisect, this used to work.

From git bisect:
    528963af5c3af95ec94407ba08ba47eda4bb88eb is the first bad commit

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/a83fcb1a30901bc2224a799cb3934af0f1287e73#diff-f90f04ba6e8699e7f5b884f4942e6caaR21
fixed
