### ISSUE TITLE
vennu, bright bird of devinity and maybe other card are wrong

### ISSUE THREAD

**Issue by AndreOliveiraMendes** [Fluorohydride/ygopro-scripts#963]
> Q. 
> Ｆ．Ａ．ハングオンマッハ + 輝神鳥ヴェーヌ 
> モンスターのレベルがすでに1増加している場合、別のレベルに設定されているとどうなりますか？ 
> A. 
> 「F.A.ハングオンマッハ」自身のレベルが1つ上がっている状況で「輝神鳥ヴェーヌ」の効果を発動した場合、その「F.A.ハングオンマッハ」のレベルは、「輝神鳥ヴェーヌ」の効果で見せたカードと同じレベルになります。
> 例えば、見せたカードのレベルが10だった場合、「F.A.ハングオンマッハ」のレベルは10になります。
------------------------------------------------------------------------------------------------
> Q.
> F. A. Hang-On Mach + Shinto Shinto Venue
> What happens if the monster level has already increased by 1, if it is set to a different level?
> A.
> In the situation where "FA Hang-on-Mach" itself is raised by one level, when activating the effect of "Shinjinkori Venu", the level of that "FA Hang-on Mach" is the card that I showed through the effect of "Shinjinkori Venu" It will be on the same level.
> For example, if the displayed card level is 10, the level of "F.A. Hang-on Mach" will be 10.
> 

current in ygopro it turn into level 11, so it wrong.

**Comment by DailyShana** [comment]
89b0483b340791610f316e7ce20f929705d9402e
