### ISSUE TITLE
Can activate cards in an "illegal" zone

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro-scripts#977]
with a field like this
![image](https://user-images.githubusercontent.com/18705342/33093584-a471e15c-cefd-11e7-993d-c7194f2df373.png)
and with valid targets fro "Draco Face-Off" i can activate the card IN the rightmost zone, the pendulum zone, making the activation invalid because in that way, the effect won't be able to resolve, because the pzone is locked with the spell itself and vanity's emptiniess prevents you from special summoning. Thus it's needed a way to check the valid sequences where to  activate the card, in this case, you should be forced to activate it in the other zone, the one that isn't a pzone, to prevent illegal moves.

**Comment by purerosefallen** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/6d6029bc92b22fcfd151233cc4435503291511cb
This may solve.
