### ISSUE TITLE
Link + Fusion + Reborn - Wrong place of fusion monsters?

### ISSUE THREAD

**Issue by fervi** [Fluorohydride/ygopro-scripts#985]
![ygobug](https://user-images.githubusercontent.com/2242925/33743314-99896fb0-dbac-11e7-9271-bc137ac23df2.png)

Ok, so if I summon fusion monster it appear on link (?) position (not like always - it is corrent? I don't play in this crappy version of Yu-gi-oh)

If it is correct - Call of the haunted summon Fusion monster (after dead) on normal Monster field. And it isn't probably correct (I think)

Is it a bug?

**Comment by DailyShana** [comment]
http://yugioh.wikia.com/wiki/Extra_Monster_Zone
